BEGIN;

TRUNCATE
  stories,
  images,
  users
  RESTART IDENTITY CASCADE;

INSERT INTO images (link, alt)
VALUES
  ('https://bedtime-images.s3.us-west-1.amazonaws.com/1556344646856_img_1.jpg', 'story 1 cover'),
  ('https://bedtime-images.s3.us-west-1.amazonaws.com/1556578398932_img_6.jpg', 'story 2 cover'),
  ('https://bedtime-images.s3.us-west-1.amazonaws.com/1556578378639_img_4.jpg', 'story 3 cover'),
  ('https://bedtime-images.s3.us-west-1.amazonaws.com/1556578518243_img_3.jpg', 'story 4 cover'),
  ('https://bedtime-images.s3.us-west-1.amazonaws.com/1556344646856_img_1.jpg', 'story 1 image'),
  ('https://bedtime-images.s3.us-west-1.amazonaws.com/1556344646856_img_1.jpg', 'story 2 image'),
  ('https://bedtime-images.s3.us-west-1.amazonaws.com/1556344646856_img_1.jpg', 'story 3 image');

INSERT INTO stories (author, name, description, cover, content)
VALUES
  (
    'John Doe',
    'Lorem Ipsum',
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    '1',
    '<p>Once upon a time there was an old woman who loved baking gingerbread. She would bake gingerbread cookies, cakes, houses and gingerbread people, all decorated with chocolate and peppermint, caramel candies and colored frosting.</p>
    <p>She lived with her husband on a farm at the edge of town. The sweet spicy smell of gingerbread brought children skipping and running to see what would be offered that day.</p>
    <p>Unfortunately the children gobbled up the treats so fast that the old woman had a hard time keeping her supply of flour and spices to continue making the batches of gingerbread. Sometimes she suspected little hands of having reached through her kitchen window because gingerbread pieces and cookies would disappear. One time a whole gingerbread house vanished mysteriously.</p>
    <img src="http://www.magickeys.com/books/gingerbread/page1.jpg"/>'  
  ),
  (
    'Jane Smith',
    'Dolor Ipsum',
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    '2',
    '<h1>Lorem ipsum dolor sit amet</h1>, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet tellus cras adipiscing. Id semper risus in hendrerit gravida rutrum. In est ante in nibh mauris cursus. Suspendisse potenti nullam ac tortor. Aliquam ut porttitor leo a. Commodo nulla facilisi nullam vehicula. Mollis aliquam ut porttitor leo. Odio euismod lacinia at quis risus sed vulputate odio ut. Dignissim enim sit amet venenatis urna. Erat imperdiet sed euismod nisi porta lorem mollis aliquam ut. Suspendisse faucibus interdum posuere lorem ipsum dolor sit amet. Morbi tincidunt augue interdum velit. Eleifend mi in nulla posuere sollicitudin. Eget mauris pharetra et ultrices neque ornare aenean. Venenatis a condimentum vitae sapien pellentesque habitant morbi tristique. Mauris ultrices eros in cursus turpis. Lorem donec massa sapien faucibus et molestie ac feugiat. Augue neque gravida in fermentum et.
    Eget dolor morbi non arcu risus quis varius quam quisque. Amet aliquam id diam maecenas ultricies. Vel facilisis volutpat est velit. Urna porttitor rhoncus dolor purus. Consequat id porta nibh venenatis cras sed felis eget velit. Lobortis mattis aliquam faucibus purus in massa. Eu tincidunt tortor aliquam nulla facilisi cras fermentum odio eu. Arcu cursus euismod quis viverra nibh cras. Aliquet lectus proin nibh nisl condimentum id venenatis a condimentum. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget egestas. Et tortor consequat id porta nibh venenatis. Feugiat vivamus at augue eget arcu. Luctus accumsan tortor posuere ac ut consequat semper viverra. Urna condimentum mattis pellentesque id nibh tortor id aliquet. Faucibus et molestie ac feugiat sed lectus. Malesuada fames ac turpis egestas. Leo vel orci porta non. Nec dui nunc mattis enim ut tellus elementum sagittis. Maecenas volutpat blandit aliquam etiam erat velit. Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam.
    In massa tempor nec feugiat nisl pretium fusce id. Ac turpis egestas sed tempus urna et. Mattis pellentesque id nibh tortor id aliquet lectus proin nibh. Erat pellentesque adipiscing commodo elit at imperdiet dui. Faucibus purus in massa tempor nec feugiat nisl pretium fusce. Lacus sed viverra tellus in hac habitasse platea dictumst vestibulum. Nibh sit amet commodo nulla facilisi nullam. Lectus nulla at volutpat diam ut venenatis. Cursus mattis molestie a iaculis at erat pellentesque adipiscing. Condimentum id venenatis a condimentum vitae sapien pellentesque habitant morbi. Libero enim sed faucibus turpis in.
    A diam sollicitudin tempor id eu nisl nunc mi. Nullam vehicula ipsum a arcu cursus vitae congue mauris rhoncus. Nisl pretium fusce id velit ut tortor. Ut tellus elementum sagittis vitae et. Maecenas pharetra convallis posuere morbi. Quis hendrerit dolor magna eget. Morbi non arcu risus quis varius. Iaculis nunc sed augue lacus viverra vitae congue. Tristique nulla aliquet enim tortor at auctor. Blandit massa enim nec dui nunc. Magnis dis parturient montes nascetur ridiculus mus mauris. Aliquam nulla facilisi cras fermentum odio eu. Eu consequat ac felis donec et. Ac odio tempor orci dapibus ultrices. Augue interdum velit euismod in. Purus ut faucibus pulvinar elementum integer enim neque volutpat.
    Ac tortor vitae purus faucibus. Dignissim sodales ut eu sem integer vitae justo eget. Vulputate dignissim suspendisse in est ante in nibh. Ornare aenean euismod elementum nisi. Est ante in nibh mauris. Maecenas pharetra convallis posuere morbi leo urna molestie. Nulla facilisi etiam dignissim diam quis. In vitae turpis massa sed elementum tempus egestas sed. Enim sit amet venenatis urna cursus eget. Euismod nisi porta lorem mollis aliquam ut. Ut sem nulla pharetra diam sit amet. Ultrices eros in cursus turpis massa tincidunt dui ut. Vivamus arcu felis bibendum ut tristique et. Lectus sit amet est placerat. Senectus et netus et malesuada fames. Posuere morbi leo urna molestie at elementum eu facilisis. Egestas purus viverra accumsan in nisl nisi. Sed euismod nisi porta lorem mollis aliquam ut porttitor.'
  ),
  (
    'Jennifer Smith',
    'Aliquam Ipsum',
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    '3',
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet tellus cras adipiscing. Id semper risus in hendrerit gravida rutrum. In est ante in nibh mauris cursus. Suspendisse potenti nullam ac tortor. Aliquam ut porttitor leo a. Commodo nulla facilisi nullam vehicula. Mollis aliquam ut porttitor leo. Odio euismod lacinia at quis risus sed vulputate odio ut. Dignissim enim sit amet venenatis urna. Erat imperdiet sed euismod nisi porta lorem mollis aliquam ut. Suspendisse faucibus interdum posuere lorem ipsum dolor sit amet. Morbi tincidunt augue interdum velit. Eleifend mi in nulla posuere sollicitudin. Eget mauris pharetra et ultrices neque ornare aenean. Venenatis a condimentum vitae sapien pellentesque habitant morbi tristique. Mauris ultrices eros in cursus turpis. Lorem donec massa sapien faucibus et molestie ac feugiat. Augue neque gravida in fermentum et.
    Eget dolor morbi non arcu risus quis varius quam quisque. Amet aliquam id diam maecenas ultricies. Vel facilisis volutpat est velit. Urna porttitor rhoncus dolor purus. Consequat id porta nibh venenatis cras sed felis eget velit. Lobortis mattis aliquam faucibus purus in massa. Eu tincidunt tortor aliquam nulla facilisi cras fermentum odio eu. Arcu cursus euismod quis viverra nibh cras. Aliquet lectus proin nibh nisl condimentum id venenatis a condimentum. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget egestas. Et tortor consequat id porta nibh venenatis. Feugiat vivamus at augue eget arcu. Luctus accumsan tortor posuere ac ut consequat semper viverra. Urna condimentum mattis pellentesque id nibh tortor id aliquet. Faucibus et molestie ac feugiat sed lectus. Malesuada fames ac turpis egestas. Leo vel orci porta non. Nec dui nunc mattis enim ut tellus elementum sagittis. Maecenas volutpat blandit aliquam etiam erat velit. Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam.
    In massa tempor nec feugiat nisl pretium fusce id. Ac turpis egestas sed tempus urna et. Mattis pellentesque id nibh tortor id aliquet lectus proin nibh. Erat pellentesque adipiscing commodo elit at imperdiet dui. Faucibus purus in massa tempor nec feugiat nisl pretium fusce. Lacus sed viverra tellus in hac habitasse platea dictumst vestibulum. Nibh sit amet commodo nulla facilisi nullam. Lectus nulla at volutpat diam ut venenatis. Cursus mattis molestie a iaculis at erat pellentesque adipiscing. Condimentum id venenatis a condimentum vitae sapien pellentesque habitant morbi. Libero enim sed faucibus turpis in.
    A diam sollicitudin tempor id eu nisl nunc mi. Nullam vehicula ipsum a arcu cursus vitae congue mauris rhoncus. Nisl pretium fusce id velit ut tortor. Ut tellus elementum sagittis vitae et. Maecenas pharetra convallis posuere morbi. Quis hendrerit dolor magna eget. Morbi non arcu risus quis varius. Iaculis nunc sed augue lacus viverra vitae congue. Tristique nulla aliquet enim tortor at auctor. Blandit massa enim nec dui nunc. Magnis dis parturient montes nascetur ridiculus mus mauris. Aliquam nulla facilisi cras fermentum odio eu. Eu consequat ac felis donec et. Ac odio tempor orci dapibus ultrices. Augue interdum velit euismod in. Purus ut faucibus pulvinar elementum integer enim neque volutpat.
    Ac tortor vitae purus faucibus. Dignissim sodales ut eu sem integer vitae justo eget. Vulputate dignissim suspendisse in est ante in nibh. Ornare aenean euismod elementum nisi. Est ante in nibh mauris. Maecenas pharetra convallis posuere morbi leo urna molestie. Nulla facilisi etiam dignissim diam quis. In vitae turpis massa sed elementum tempus egestas sed. Enim sit amet venenatis urna cursus eget. Euismod nisi porta lorem mollis aliquam ut. Ut sem nulla pharetra diam sit amet. Ultrices eros in cursus turpis massa tincidunt dui ut. Vivamus arcu felis bibendum ut tristique et. Lectus sit amet est placerat. Senectus et netus et malesuada fames. Posuere morbi leo urna molestie at elementum eu facilisis. Egestas purus viverra accumsan in nisl nisi. Sed euismod nisi porta lorem mollis aliquam ut porttitor.'
  ),
  (
    'Alan Foo',
    'Eget Morbi',
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    '4',
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet tellus cras adipiscing. Id semper risus in hendrerit gravida rutrum. In est ante in nibh mauris cursus. Suspendisse potenti nullam ac tortor. Aliquam ut porttitor leo a. Commodo nulla facilisi nullam vehicula. Mollis aliquam ut porttitor leo. Odio euismod lacinia at quis risus sed vulputate odio ut. Dignissim enim sit amet venenatis urna. Erat imperdiet sed euismod nisi porta lorem mollis aliquam ut. Suspendisse faucibus interdum posuere lorem ipsum dolor sit amet. Morbi tincidunt augue interdum velit. Eleifend mi in nulla posuere sollicitudin. Eget mauris pharetra et ultrices neque ornare aenean. Venenatis a condimentum vitae sapien pellentesque habitant morbi tristique. Mauris ultrices eros in cursus turpis. Lorem donec massa sapien faucibus et molestie ac feugiat. Augue neque gravida in fermentum et.
    Eget dolor morbi non arcu risus quis varius quam quisque. Amet aliquam id diam maecenas ultricies. Vel facilisis volutpat est velit. Urna porttitor rhoncus dolor purus. Consequat id porta nibh venenatis cras sed felis eget velit. Lobortis mattis aliquam faucibus purus in massa. Eu tincidunt tortor aliquam nulla facilisi cras fermentum odio eu. Arcu cursus euismod quis viverra nibh cras. Aliquet lectus proin nibh nisl condimentum id venenatis a condimentum. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget egestas. Et tortor consequat id porta nibh venenatis. Feugiat vivamus at augue eget arcu. Luctus accumsan tortor posuere ac ut consequat semper viverra. Urna condimentum mattis pellentesque id nibh tortor id aliquet. Faucibus et molestie ac feugiat sed lectus. Malesuada fames ac turpis egestas. Leo vel orci porta non. Nec dui nunc mattis enim ut tellus elementum sagittis. Maecenas volutpat blandit aliquam etiam erat velit. Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam.
    In massa tempor nec feugiat nisl pretium fusce id. Ac turpis egestas sed tempus urna et. Mattis pellentesque id nibh tortor id aliquet lectus proin nibh. Erat pellentesque adipiscing commodo elit at imperdiet dui. Faucibus purus in massa tempor nec feugiat nisl pretium fusce. Lacus sed viverra tellus in hac habitasse platea dictumst vestibulum. Nibh sit amet commodo nulla facilisi nullam. Lectus nulla at volutpat diam ut venenatis. Cursus mattis molestie a iaculis at erat pellentesque adipiscing. Condimentum id venenatis a condimentum vitae sapien pellentesque habitant morbi. Libero enim sed faucibus turpis in.
    A diam sollicitudin tempor id eu nisl nunc mi. Nullam vehicula ipsum a arcu cursus vitae congue mauris rhoncus. Nisl pretium fusce id velit ut tortor. Ut tellus elementum sagittis vitae et. Maecenas pharetra convallis posuere morbi. Quis hendrerit dolor magna eget. Morbi non arcu risus quis varius. Iaculis nunc sed augue lacus viverra vitae congue. Tristique nulla aliquet enim tortor at auctor. Blandit massa enim nec dui nunc. Magnis dis parturient montes nascetur ridiculus mus mauris. Aliquam nulla facilisi cras fermentum odio eu. Eu consequat ac felis donec et. Ac odio tempor orci dapibus ultrices. Augue interdum velit euismod in. Purus ut faucibus pulvinar elementum integer enim neque volutpat.
    Ac tortor vitae purus faucibus. Dignissim sodales ut eu sem integer vitae justo eget. Vulputate dignissim suspendisse in est ante in nibh. Ornare aenean euismod elementum nisi. Est ante in nibh mauris. Maecenas pharetra convallis posuere morbi leo urna molestie. Nulla facilisi etiam dignissim diam quis. In vitae turpis massa sed elementum tempus egestas sed. Enim sit amet venenatis urna cursus eget. Euismod nisi porta lorem mollis aliquam ut. Ut sem nulla pharetra diam sit amet. Ultrices eros in cursus turpis massa tincidunt dui ut. Vivamus arcu felis bibendum ut tristique et. Lectus sit amet est placerat. Senectus et netus et malesuada fames. Posuere morbi leo urna molestie at elementum eu facilisis. Egestas purus viverra accumsan in nisl nisi. Sed euismod nisi porta lorem mollis aliquam ut porttitor.'
  );

INSERT INTO users (user_name, password, email, first_name, last_name)
VALUES
  ('johndoe', '$2a$04$5DS6X/TYcyMHqyoB3yAeyOjJx6ELQyT6G9DEFPeuOe4tp3YgYdDdm', 'johndoe@gmail.com', 'john', 'doe'),
  ('janesmith', '$2a$04$m63r3lAvpMB62cxH/YTiPOcVU8L5sUlPmmR.3qIX7Ro/YWmKKYjkC', 'janesmith@gmail.con', 'jane', 'smith'),
  ('olegkan', '$2a$04$6u/FzBvuaDilXDwgNUGvgegP.dHdsg.TyKTqP1yP1MUNPFkkCnz86', 'olegkan@gmail.con', 'oleg', 'kan'),
  ('guest', '$2a$04$DUKQY.R3ggoCKqy104t0ZuAuGAlt3S0q3DekPtQsKGHd1S4sIJ65y', 'guest@guest.guest', 'Hello', 'Guest!');

COMMIT;